# Site settings
title: MIVEHIND
email: rharwood@club.cc.cmu.edu
description: "MIVEHIND/out.log - Philosophy and systems in linear combination"
baseurl: ""
url: "https://mivehind.net"

# Build settings
markdown: redcarpet
permalink: pretty
highlighter: pygments
destination: /var/www/html
encoding: utf-8
